#!/bin/bash

#echo -e "Content-type: text/html\r\n\r\n"
echo -e "Content-Type: audio/mpeg\r\n\r\n"

tune_enc="$QUERY_STRING"
tune_file=/var/www`urlencode -d $tune_enc`

if [ `echo "$tune_file" | grep -P -i "\.mp3$"` ]; then 
    lame -abr -V 9 -q 9 "$tune_file" -
else
    cat "$tune_file"
fi

