#!/bin/bash
echo -e "Content-type: text/html\r\n\r\n"

tune=`find /var/www/music/* | grep -P "\.(mp3|m4a)$" | sort -R | head -n 1`
wwwtune=`echo $tune | sed 's!^/var/www!!'`

cat << HEADER
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <style>
      a#next_tune {background-color:yellow; border:1px solid black; padding:5px; text-decoration:none}
    </style>
  </head>
<body>
HEADER

echo '<a href="'$wwwtune'">'$wwwtune'</a><p>'

cat << PLAYER
<audio id="player" controls autoplay>
    <source src="http://192.168.2.11/cgi-bin/testlame?$wwwtune" type="audio/mpeg">
    Your browser does not support the audio element
</audio>
PLAYER
echo '<p>'

echo '<a id="next_tune" href="'/cgi-bin/tunemate'">'Next tune'</a><p>'

eyeD3 --no-color "$tune" | sed 's/$/<br>/' 
echo '<p>'

#echo $QUERY_STRING
#echo '<p>'
#
#IN="bla@some.com;john@home.com"
#
#arr=$(echo $IN | tr ";" "\n")
#
#for x in $arr; do
#    echo "> [$x]"
#done

#find /var/www/music/* | grep -P "\.(mp3|m4a)$" | sort -R | head -n 10  | sed 's/$/<br>/'

cat << SCRIPTS
<script>
  var aud = document.getElementById("player");
  aud.onended = function() {
    window.location.href = "/cgi-bin/tunemate";
  };
  //aud.play();
</script>
SCRIPTS

cat << FOOTER
</body>
</html>
FOOTER

